# Generated by Django 4.2.16 on 2024-12-14 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_produto_alter_categoria_options_categoria_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
